### ISSUE TITLE
Das Löschen vom Computern und Schulen sollte den gleichen Nachfrage Dialog erhalten wie das Löschen von Teams

### ISSUE THREAD

**Issue by rokka** [rokka/hey-alter-admin#4]
![image](https://user-images.githubusercontent.com/533290/115134976-36423c80-a015-11eb-909f-2e618e3af01e.png)

**Comment by funakova** [comment]
https://github.com/rokka/hey-alter-admin/pull/11

**Comment by rokka** [comment]
Done
