### ISSUE TITLE
UpdateTeamName.php soll in UpdateTeam.php umbenannt werden

### ISSUE THREAD

**Issue by rokka** [rokka/hey-alter-admin#5]
Da diese Klasse nicht mehr nur den Teamnamen sondern weitere Team-Eigenschaften ändert.

Dazu bitte im Code nach "UpdateTeamName" suchen und diese ersetzen.

Danach sollte das Anlegen und Editieren getestet werden.

**Comment by funakova** [comment]
Siehe: https://github.com/rokka/hey-alter-admin/pull/8
