### ISSUE TITLE
Testzugangsdaten Anzeige durch Link ersetzen

### ISSUE THREAD

**Issue by rokka** [rokka/hey-alter-admin#6]
![image](https://user-images.githubusercontent.com/533290/115135167-81108400-a016-11eb-884b-85f772d9e5c1.png)

"Testzugang: test@heyalter.com // testtest" soll durch einen Link "Testzugang verwenden" ersetzt werden. Klickt man diesen an soll das Feld für Benutzername und Passwort mit "test@heyalter.com // testtest" gefüllt werden und der Login Button geklickt werden.

**Comment by funakova** [comment]
Siehe https://github.com/rokka/hey-alter-admin/pull/10

**Comment by rokka** [comment]
Done

**Comment by rokka** [comment]
Kannst du das bitte noch ein wenig verschieben?

![image](https://user-images.githubusercontent.com/533290/116457378-9f228380-a863-11eb-8959-e872b7805225.png)

**Comment by funakova** [comment]
https://github.com/rokka/hey-alter-admin/pull/11
